app = "lexium-api-marcelo-20251003x"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

[[mounts]]
  source = "data_vol"
  destination = "/app/storage"

[env]
  ADMIN_TOKEN = "lexium123"     # solo para el demo
  CORS_ORIGINS = "*"            # para probar desde cualquier origen
  # (opcional, solo si quieres probar /api/answer sin secrets)
  # OPENAI_API_KEY = "sk-xxxxxxxx"
