name: Fly Start Machines
on:
  workflow_dispatch: {}
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
  FLY_REGION: ${{ secrets.FLY_REGION }}
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: List machines
        run: flyctl machines list -a "$FLY_APP_NAME" --json | jq -r '.[] | {id, state}'
      - name: Start machines (if any are stopped)
        run: |
          MIDS=$(flyctl machines list -a "$FLY_APP_NAME" --json | jq -r '.[].id')
          if [ -z "$MIDS" ]; then
            echo "No hay máquinas. Hago deploy para crear una."
            flyctl deploy -a "$FLY_APP_NAME" --remote-only
          else
            for id in $MIDS; do
              echo "Iniciando $id"
              flyctl machine start "$id" -a "$FLY_APP_NAME" --yes || true
            done
          fi
