name: Deploy to Fly

on:
  push:
    branches: [ main ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
  FLY_REGION: ${{ secrets.FLY_REGION }}
  FLY_ORG: ${{ secrets.FLY_ORG }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      # (DEBUG) Ver owner/org actuales
      - name: Debug whoami
        run: |
          flyctl auth whoami || true

      # Crea la app en la ORG correcta (idempotente)
      - name: Ensure app exists (org)
        run: |
          flyctl apps create "$FLY_APP_NAME" -o "$FLY_ORG" || true

      # (DEBUG) Lista apps en la ORG para ver el nombre real
      - name: List apps in org
        run: |
          flyctl apps list -o "$FLY_ORG" || true

      # Crea volumen persistente si no existe
      - name: Ensure volume exists
        run: |
          flyctl volumes list -a "$FLY_APP_NAME" | grep -q data_vol || \
          flyctl volumes create data_vol --region "$FLY_REGION" --size 1 -a "$FLY_APP_NAME"

      # Define secrets de la app (repetible)
      - name: Set app secrets
        run: |
          flyctl secrets set -a "$FLY_APP_NAME" \
            OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' \
            ADMIN_TOKEN='${{ secrets.ADMIN_TOKEN }}' \
            --stage

      # Despliegue usando Dockerfile de la raíz
      - name: Deploy
        run: |
          flyctl deploy -a "$FLY_APP_NAME" --remote-only

      # (DEBUG) Muestra info con hostname exacto
      - name: Show app info
        run: |
          flyctl info -a "$FLY_APP_NAME" || true

      # (DEBUG) Estado/máquinas
      - name: Status
        run: |
          flyctl status -a "$FLY_APP_NAME" || true
