name: Fly: Set Secrets
on: { workflow_dispatch: {} }

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Sanity-check
        run: |
          test -n "$FLY_API_TOKEN" || (echo "Missing FLY_API_TOKEN" && exit 1)
          test -n "$FLY_APP_NAME" || (echo "Missing FLY_APP_NAME" && exit 1)

      - name: Set secrets on Fly app
        run: |
          flyctl secrets set -a "$FLY_APP_NAME" \
            ADMIN_TOKEN='${{ secrets.ADMIN_TOKEN }}' \
            OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' \
            CORS_ORIGINS='${{ secrets.CORS_ORIGINS }}'

      - name: Verify
        run: flyctl secrets list -a "$FLY_APP_NAME" || true
