name: Stop App Machines

on:
  workflow_dispatch: {}

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP: ${{ secrets.APP_TO_DESTROY }}

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: |
          MIDS=$(flyctl machines list -a "$APP" --json | jq -r '.[].id' || true)
          for id in $MIDS; do
            echo "Stopping $id"
            flyctl machine stop "$id" -a "$APP" --yes || true
          done
