name: Fly: Set Secrets
on: { workflow_dispatch: {} }
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
jobs:
  set:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Set secrets
        run: |
          flyctl secrets set -a "$FLY_APP_NAME" \
            OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' \
            ADMIN_TOKEN='${{ secrets.ADMIN_TOKEN }}' \
            CORS_ORIGINS='${{ secrets.CORS_ORIGINS }}'
      - name: Verify
        run: flyctl secrets list -a "$FLY_APP_NAME" || true
