name: Fly: Set Secrets
on:
  workflow_dispatch: {}

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Set app secrets (OPENAI_API_KEY, ADMIN_TOKEN)
        run: |
          flyctl secrets set -a "$FLY_APP_NAME" \
            OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' \
            ADMIN_TOKEN='${{ secrets.ADMIN_TOKEN }}'

      - name: Verify (list secret names)
        run: flyctl secrets list -a "$FLY_APP_NAME" || true
