name: Fly App Audit
on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Fly app name (e.g., lexium-api-marcelo)'
        required: true
jobs:
  audit:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      APP: ${{ github.event.inputs.app }}
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - run: sudo apt-get update && sudo apt-get install -y jq
      - name: Status
        run: flyctl status -a "$APP" || true
      - name: Machines
        run: flyctl machines list -a "$APP" --json | jq '. | length as $n | "machines: \($n)\n", .[] | {id,region,state,config:{mounts}}' || true
      - name: Volumes
        run: flyctl volumes list -a "$APP" || true
